CREATE DATABASE IF NOT EXISTS mascotadb DEFAULT CHARACTER SET utf8 ;

USE mascotadb;

CREATE TABLE IF NOT EXISTS pets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    status ENUM("ALIVE", "DEAD") DEFAULT "ALIVE" NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
